services:
  ollama:
    restart: always
    image: ollama/ollama
    volumes:
      - ./ollama:/root/.ollama
  beat: 
    restart: always
    build: .
    depends_on:
      - ollama
    command: python main.py
    volumes:
      - .:/code

