services:
  nvidia:
    image: selenium/node-chrome:3.141.59
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

      environment:
        - NVIDIA_VISIBLE_DEVICES=all
    restart: always
    tty: true
    command: [ "nvidia-smi" ]
