FROM python:3.10.6-bullseye
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=UTF-8
WORKDIR /sdtemp
RUN python -m pip install --upgrade pip wheel
RUN apt-get update &&\
    apt-get install -y wget git
RUN git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui /sdtemp

#torch and torchvision version number refer to
#https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/launch.py
ENV python -m pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
ENV TORCH_COMMAND="pip install torch torchvision torchaudio"
RUN python -m $TORCH_COMMAND

RUN python launch.py --exit
RUN python -m pip install opencv-python-headless
WORKDIR /stablediff-web